# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
