# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0013_auto_20160620_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='extra',
            name='profileimage',
            field=models.ImageField(blank=True, upload_to='profilepics'),
        ),
    ]
