# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0016_auto_20160621_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to=settings.AUTH_USER_MODEL),
        ),
    ]
