# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
