# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='username',
            field=models.CharField(max_length=301),
        ),
    ]
