# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20160616_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 12, 35, 54, 91279)),
        ),
    ]
