# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_auto_20160620_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='profileimage',
            field=models.ImageField(upload_to='profilepics'),
        ),
    ]
