# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 22:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0015_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='original',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='original', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
